export const COLORS = {
  primary: '#16a34a',
  primaryDark: '#15803d',
  primaryLight: '#dcfce7',
  accent: '#22c55e',
  bg: '#0f172a',
  card: '#1e293b',
  card2: '#263448',
  border: '#334155',
  text: '#f1f5f9',
  sub: '#94a3b8',
  danger: '#ef4444',
  warning: '#f59e0b',
  info: '#3b82f6',
  yellow: '#eab308',
  pink: '#ec4899',
  purple: '#a855f7',
  cyan: '#06b6d4',
};

// ─── USERS & CUSTOMERS CRM ───────────────────────────────────────────────────
export const USERS_DB = [
  {
    id: 'admin1',
    name: 'Trần Quốc Trung (Super Admin)',
    email: 'admin@court.vn',
    password: '123456',
    role: 'admin', // admin | manager | staff | customer
    phone: '0905 591 379',
    status: 'active', // active | locked
    joinedDate: '01/01/2026',
    totalSpent: 0,
    bookingsCount: 0,
    tier: 'Kim Cương',
  },
  {
    id: 'manager1',
    name: 'Nguyễn Văn Quản Lý',
    email: 'manager@court.vn',
    password: '123456',
    role: 'manager',
    phone: '0912 345 678',
    status: 'active',
    joinedDate: '15/01/2026',
    totalSpent: 0,
    bookingsCount: 0,
    tier: 'Vàng',
  },
  {
    id: 'staff1',
    name: 'Lê Thu Ngân (Lễ tân)',
    email: 'staff@court.vn',
    password: '123456',
    role: 'staff',
    phone: '0935 111 222',
    status: 'active',
    joinedDate: '01/02/2026',
    totalSpent: 0,
    bookingsCount: 0,
    tier: 'Bạc',
  },
  {
    id: 'user1',
    name: 'Trung Quốc (Khách VIP)',
    email: 'trung05082005tqt@gmail.com',
    password: '123456',
    role: 'customer',
    phone: '0905591379',
    status: 'active',
    joinedDate: '10/02/2026',
    totalSpent: 2850000,
    bookingsCount: 18,
    tier: 'Kim Cương',
  },
  {
    id: 'user2',
    name: 'Hoàng Minh Đức',
    email: 'duc.hoang@gmail.com',
    password: '123456',
    role: 'customer',
    phone: '0905 888 777',
    status: 'active',
    joinedDate: '20/02/2026',
    totalSpent: 1420000,
    bookingsCount: 9,
    tier: 'Vàng',
  },
  {
    id: 'user3',
    name: 'Phạm Thị Mai',
    email: 'mai.pham@gmail.com',
    password: '123456',
    role: 'customer',
    phone: '0914 222 333',
    status: 'active',
    joinedDate: '05/03/2026',
    totalSpent: 650000,
    bookingsCount: 4,
    tier: 'Bạc',
  },
  {
    id: 'user4',
    name: 'Đặng Tuấn Anh',
    email: 'tuananh@gmail.com',
    password: '123456',
    role: 'customer',
    phone: '0978 999 000',
    status: 'locked',
    joinedDate: '12/03/2026',
    totalSpent: 160000,
    bookingsCount: 1,
    tier: 'Đồng',
  },
];

// ─── COURTS DATA WITH 4 STATES ───────────────────────────────────────────────
// status: 'available' (Trống) | 'booked' (Đã đặt) | 'in_use' (Đang sử dụng) | 'maintenance' (Bảo trì)
export const COURTS_DATA = [
  {
    id: '1',
    name: 'Sân 1 - TPT Sport',
    clubId: 'c1',
    clubName: 'CLB Cầu Lông TPT Sport',
    location: '207 Quách Thị Trang, Hòa Xuân, Cẩm Lệ, Đà Nẵng',
    district: 'Cẩm Lệ',
    price: 80000,
    type: 'Thảm PVC thi đấu',
    status: 'in_use',
    currentGuest: 'Hoàng Minh Đức (0905 888 777)',
    currentSlot: '10:00 - 12:00',
  },
  {
    id: '2',
    name: 'Sân 2 - TPT Sport',
    clubId: 'c1',
    clubName: 'CLB Cầu Lông TPT Sport',
    location: '207 Quách Thị Trang, Hòa Xuân, Cẩm Lệ, Đà Nẵng',
    district: 'Cẩm Lệ',
    price: 80000,
    type: 'Thảm PVC thi đấu',
    status: 'available',
    currentGuest: null,
    currentSlot: null,
  },
  {
    id: '3',
    name: 'Sân 1 - Ngôi Hoàng',
    clubId: 'c2',
    clubName: 'CN 3_CLB Tennis & Cầu Lông Ngôi Hoàng',
    location: '207 Quách Thị Trang, Hòa Xuân, Cẩm Lệ, Đà Nẵng',
    district: 'Cẩm Lệ',
    price: 90000,
    type: 'Sàn gỗ cao cấp',
    status: 'booked',
    currentGuest: 'Trung Quốc (0905591379)',
    currentSlot: '17:00 - 19:00',
  },
  {
    id: '4',
    name: 'Sân 2 - Ngôi Hoàng',
    clubId: 'c2',
    clubName: 'CN 3_CLB Tennis & Cầu Lông Ngôi Hoàng',
    location: '207 Quách Thị Trang, Hòa Xuân, Cẩm Lệ, Đà Nẵng',
    district: 'Cẩm Lệ',
    price: 90000,
    type: 'Sàn gỗ cao cấp',
    status: 'available',
    currentGuest: null,
    currentSlot: null,
  },
  {
    id: '5',
    name: 'Sân 1 - Nestworld',
    clubId: 'c3',
    clubName: 'NESTWORLD BADMINTON CLUB',
    location: '12 Trịnh Công Sơn, Hòa Cường Nam, Hải Châu, Đà Nẵng',
    district: 'Hải Châu',
    price: 100000,
    type: 'Thảm tiêu chuẩn BWF',
    status: 'in_use',
    currentGuest: 'Phạm Thị Mai (0914 222 333)',
    currentSlot: '09:00 - 11:00',
  },
  {
    id: '6',
    name: 'Sân 2 - Nestworld',
    clubId: 'c3',
    clubName: 'NESTWORLD BADMINTON CLUB',
    location: '12 Trịnh Công Sơn, Hòa Cường Nam, Hải Châu, Đà Nẵng',
    district: 'Hải Châu',
    price: 100000,
    type: 'Thảm tiêu chuẩn BWF',
    status: 'maintenance',
    currentGuest: 'Đang bảo dưỡng đèn LED',
    currentSlot: 'Tạm ngưng đến 14:00',
  },
  {
    id: '7',
    name: 'Sân 1 - Icons',
    clubId: 'c4',
    clubName: 'ICONS Badminton & Pickleball',
    location: '122 Tôn Đản, Hòa An, Cẩm Lệ, Đà Nẵng',
    district: 'Cẩm Lệ',
    price: 80000,
    type: 'Sân đa năng Pickleball/Cầu lông',
    status: 'available',
    currentGuest: null,
    currentSlot: null,
  },
  {
    id: '8',
    name: 'Sân 1 - Quân Khu 5',
    clubId: 'c6',
    clubName: 'Sân Cầu Lông Quân Khu 5',
    location: '07 Duy Tân, Hòa Cường Bắc, Hải Châu, Đà Nẵng',
    district: 'Hải Châu',
    price: 120000,
    type: 'Nhà thi đấu khán đài VIP',
    status: 'booked',
    currentGuest: 'CLB Doanh Nhân Đà Nẵng',
    currentSlot: '18:00 - 21:00',
  },
];

// Hours from 5:00 to 22:00
export const HOURS = [];
for (let h = 5; h <= 22; h++) {
  HOURS.push(`${h}:00`);
}

// Pre-booked slots: { courtId, hour }
export const INITIAL_BOOKED = [
  { courtId: '1', hour: 8 }, { courtId: '1', hour: 9 }, { courtId: '1', hour: 10 }, { courtId: '1', hour: 11 }, { courtId: '1', hour: 14 }, { courtId: '1', hour: 15 },
  { courtId: '2', hour: 7 }, { courtId: '2', hour: 10 }, { courtId: '2', hour: 18 },
  { courtId: '3', hour: 6 }, { courtId: '3', hour: 7 }, { courtId: '3', hour: 17 }, { courtId: '3', hour: 18 },
  { courtId: '4', hour: 8 }, { courtId: '4', hour: 9 }, { courtId: '4', hour: 10 },
  { courtId: '5', hour: 9 }, { courtId: '5', hour: 10 }, { courtId: '5', hour: 19 }, { courtId: '5', hour: 20 },
  { courtId: '6', hour: 7 }, { courtId: '6', hour: 8 }, { courtId: '6', hour: 9 }, { courtId: '6', hour: 10 }, { courtId: '6', hour: 11 }, { courtId: '6', hour: 12 }, { courtId: '6', hour: 13 },
  { courtId: '7', hour: 9 }, { courtId: '7', hour: 10 }, { courtId: '7', hour: 18 },
  { courtId: '8', hour: 18 }, { courtId: '8', hour: 19 }, { courtId: '8', hour: 20 },
];

// ─── SERVICES & INVENTORY ───────────────────────────────────────────────────
export const SERVICES_DATA = [
  { id: 's1', name: 'Nước khoáng Aquafina (500ml)', category: 'Nước uống', price: 10000, cost: 5000, stock: 120, unit: 'Chai' },
  { id: 's2', name: 'Nước điện giải Revive bù khoáng', category: 'Nước uống', price: 15000, cost: 8000, stock: 85, unit: 'Chai' },
  { id: 's3', name: 'Pocari Sweat ion supply', category: 'Nước uống', price: 20000, cost: 12000, stock: 45, unit: 'Chai' },
  { id: 's4', name: 'Bò húc RedBull Thái Lan', category: 'Nước uống', price: 20000, cost: 12000, stock: 32, unit: 'Lon' },
  { id: 's5', name: 'Ống cầu lông Hải Yến S90 (12 quả)', category: 'Dụng cụ', price: 240000, cost: 195000, stock: 18, unit: 'Ống' },
  { id: 's6', name: 'Ống cầu lông Yonex AS-40', category: 'Dụng cụ', price: 420000, cost: 350000, stock: 6, unit: 'Ống' },
  { id: 's7', name: 'Thuê vợt Yonex Astrox 88D (1 lượt)', category: 'Cho thuê', price: 30000, cost: 0, stock: 15, unit: 'Cây/lượt' },
  { id: 's8', name: 'Thuê vợt Lining Tectonic 7', category: 'Cho thuê', price: 25000, cost: 0, stock: 10, unit: 'Cây/lượt' },
  { id: 's9', name: 'Thuê giày cầu lông (kèm tất sạch)', category: 'Cho thuê', price: 30000, cost: 5000, stock: 20, unit: 'Đôi/lượt' },
  { id: 's10', name: 'Dịch vụ căng cước vợt 4 nút chuẩn BWF', category: 'Dịch vụ', price: 80000, cost: 40000, stock: 999, unit: 'Lần' },
  { id: 's11', name: 'Quấn cán vợt VS Grip chống mồ hôi', category: 'Dụng cụ', price: 15000, cost: 7000, stock: 65, unit: 'Cái' },
];

// ─── INITIAL BOOKINGS WITH FULL STATUSES ─────────────────────────────────────
// status: 'pending' (Chờ duyệt) | 'confirmed' (Đã xác nhận) | 'in_use' (Đang chơi) | 'completed' (Hoàn thành) | 'cancelled' (Đã hủy)
export const INITIAL_ADMIN_BOOKINGS = [
  {
    id: 'BK-1001',
    court: COURTS_DATA[0], // Sân 1 - TPT Sport
    userId: 'user2',
    userName: 'Hoàng Minh Đức',
    userPhone: '0905 888 777',
    date: '28/08/2026',
    slot: '10:00 - 12:00',
    hoursCount: 2,
    totalPrice: 160000,
    servicesAdded: [{ name: 'Nước điện giải Revive', qty: 2, price: 30000 }],
    grandTotal: 190000,
    paymentMethod: 'Chuyển khoản QR',
    paymentStatus: 'paid',
    status: 'in_use',
    note: 'Yêu cầu bật đèn sáng tối đa',
    createdAt: '28/08/2026 09:30',
  },
  {
    id: 'BK-1002',
    court: COURTS_DATA[2], // Sân 1 - Ngôi Hoàng
    userId: 'user1',
    userName: 'Trung Quốc',
    userPhone: '0905591379',
    date: '28/08/2026',
    slot: '17:00 - 19:00',
    hoursCount: 2,
    totalPrice: 180000,
    servicesAdded: [{ name: 'Ống cầu Hải Yến S90', qty: 1, price: 240000 }],
    grandTotal: 420000,
    paymentMethod: 'VNPay',
    paymentStatus: 'paid',
    status: 'confirmed',
    note: 'Đặt lịch sinh hoạt định kỳ tuần',
    createdAt: '28/08/2026 08:15',
  },
  {
    id: 'BK-1003',
    court: COURTS_DATA[4], // Sân 1 - Nestworld
    userId: 'user3',
    userName: 'Phạm Thị Mai',
    userPhone: '0914 222 333',
    date: '28/08/2026',
    slot: '09:00 - 11:00',
    hoursCount: 2,
    totalPrice: 200000,
    servicesAdded: [{ name: 'Thuê vợt Yonex', qty: 2, price: 60000 }],
    grandTotal: 260000,
    paymentMethod: 'Tiền mặt',
    paymentStatus: 'paid',
    status: 'in_use',
    note: 'Khách thanh toán trực tiếp tại quầy',
    createdAt: '28/08/2026 08:50',
  },
  {
    id: 'BK-1004',
    court: COURTS_DATA[7], // Sân 1 - Quân Khu 5
    userId: 'user2',
    userName: 'Hoàng Minh Đức',
    userPhone: '0905 888 777',
    date: '28/08/2026',
    slot: '18:00 - 21:00',
    hoursCount: 3,
    totalPrice: 360000,
    servicesAdded: [],
    grandTotal: 360000,
    paymentMethod: 'Chuyển khoản QR',
    paymentStatus: 'pending',
    status: 'pending',
    note: 'Chờ đối soát bill ngân hàng',
    createdAt: '28/08/2026 10:10',
  },
  {
    id: 'BK-1005',
    court: COURTS_DATA[1], // Sân 2 - TPT Sport
    userId: 'user1',
    userName: 'Trung Quốc',
    userPhone: '0905591379',
    date: '27/08/2026',
    slot: '07:00 - 09:00',
    hoursCount: 2,
    totalPrice: 160000,
    servicesAdded: [{ name: 'Aquafina', qty: 4, price: 40000 }],
    grandTotal: 200000,
    paymentMethod: 'Chuyển khoản QR',
    paymentStatus: 'paid',
    status: 'completed',
    note: 'Đã hoàn thành',
    createdAt: '27/08/2026 06:45',
  },
  {
    id: 'BK-1006',
    court: COURTS_DATA[3],
    userId: 'user4',
    userName: 'Đặng Tuấn Anh',
    userPhone: '0978 999 000',
    date: '27/08/2026',
    slot: '19:00 - 21:00',
    hoursCount: 2,
    totalPrice: 180000,
    servicesAdded: [],
    grandTotal: 180000,
    paymentMethod: 'Tiền mặt',
    paymentStatus: 'refunded',
    status: 'cancelled',
    note: 'Khách bận đột xuất - Hủy trước 4h',
    createdAt: '26/08/2026 14:20',
  },
];

// ─── TRANSACTIONS LOG ───────────────────────────────────────────────────────
export const TRANSACTIONS_DATA = [
  { id: 'TXN-901', bookingId: 'BK-1001', customerName: 'Hoàng Minh Đức', amount: 190000, method: 'Chuyển khoản QR', status: 'completed', time: '28/08/2026 09:35', ref: 'MB-89234821' },
  { id: 'TXN-902', bookingId: 'BK-1002', customerName: 'Trung Quốc', amount: 420000, method: 'VNPay', status: 'completed', time: '28/08/2026 08:18', ref: 'VNP-1823901' },
  { id: 'TXN-903', bookingId: 'BK-1003', customerName: 'Phạm Thị Mai', amount: 260000, method: 'Tiền mặt', status: 'completed', time: '28/08/2026 08:52', ref: 'CASH-POS1' },
  { id: 'TXN-904', bookingId: 'BK-1004', customerName: 'Hoàng Minh Đức', amount: 360000, method: 'Chuyển khoản QR', status: 'pending', time: '28/08/2026 10:10', ref: 'VCB-Pending' },
  { id: 'TXN-905', bookingId: 'BK-1005', customerName: 'Trung Quốc', amount: 200000, method: 'Chuyển khoản QR', status: 'completed', time: '27/08/2026 06:48', ref: 'MB-7712399' },
  { id: 'TXN-906', bookingId: 'BK-1006', customerName: 'Đặng Tuấn Anh', amount: 180000, method: 'Tiền mặt', status: 'refunded', time: '27/08/2026 15:00', ref: 'REFUND-001' },
];

// ─── SYSTEM AUDIT & ACTIVITY LOGS ───────────────────────────────────────────
export const ACTIVITY_LOGS = [
  { id: 'L-1', action: 'Duyệt đơn đặt sân', detail: 'Admin xác nhận đơn BK-1002 cho Trung Quốc', user: 'Trần Quốc Trung', time: '10:15 - Hôm nay', type: 'booking' },
  { id: 'L-2', action: 'Cập nhật trạng thái sân', detail: 'Chuyển Sân 1 - TPT Sport sang Đang sử dụng', user: 'Lê Thu Ngân', time: '10:00 - Hôm nay', type: 'court' },
  { id: 'L-3', action: 'Xuất kho sản phẩm', detail: 'Bán 2 chai Revive cho đơn BK-1001', user: 'Lê Thu Ngân', time: '09:35 - Hôm nay', type: 'service' },
  { id: 'L-4', action: 'Bảo trì sân đấu', detail: 'Đặt Sân 2 - Nestworld sang Bảo dưỡng đèn LED', user: 'Nguyễn Văn Quản Lý', time: '07:30 - Hôm nay', type: 'court' },
  { id: 'L-5', action: 'Khóa tài khoản', detail: 'Khóa tài khoản Đặng Tuấn Anh do vi phạm hủy giờ sát', user: 'Trần Quốc Trung', time: '27/08/2026 16:00', type: 'security' },
];

// ─── CLUBS LIST ─────────────────────────────────────────────────────────────
export const CLUBS = [
  {
    id: 'c1',
    name: 'CLB Cầu Lông TPT Sport',
    address: '207 Quách Thị Trang, Hòa Xuân, Cẩm Lệ, Đà Nẵng',
    district: 'Cẩm Lệ',
    rating: 4.9,
    reviewsCount: 128,
    distance: '2.1 km',
    open: '05:00 - 24:00',
    tag: ['Đơn ngày', 'Sự kiện'],
    lat: 15.9982,
    lng: 108.2145,
    totalCourts: 8,
    priceRange: '80.000đ - 120.000đ/h',
    phone: '0905 591 379',
    amenities: ['Wifi', 'Nước uống', 'Gửi xe miễn phí', 'Căng vợt'],
  },
  {
    id: 'c2',
    name: 'CN 3_CLB Tennis & Cầu Lông Ngôi Hoàng',
    address: '207 Quách Thị Trang, Hòa Xuân, Cẩm Lệ, Đà Nẵng',
    district: 'Cẩm Lệ',
    rating: 4.8,
    reviewsCount: 96,
    distance: '3.5 km',
    open: '05:00 - 23:00',
    tag: ['Đơn ngày', 'Sự kiện'],
    lat: 16.0025,
    lng: 108.2098,
    totalCourts: 6,
    priceRange: '90.000đ - 130.000đ/h',
    phone: '0905 123 456',
    amenities: ['Máy lạnh', 'Phòng tắm', 'Căng tin', 'Shop đồ tập'],
  },
  {
    id: 'c3',
    name: 'NESTWORLD BADMINTON CLUB',
    address: '12 Trịnh Công Sơn, Hòa Cường Nam, Hải Châu, Đà Nẵng',
    district: 'Hải Châu',
    rating: 5.0,
    reviewsCount: 215,
    distance: '1.2 km',
    open: '05:00 - 22:00',
    tag: ['Đơn ngày', 'Sự kiện'],
    lat: 16.0354,
    lng: 108.2238,
    totalCourts: 10,
    priceRange: '100.000đ - 150.000đ/h',
    phone: '0935 888 999',
    amenities: ['Thảm thi đấu quốc tế', 'Đèn chống chói', 'Wifi 6', 'Ghế khán giả'],
  },
  {
    id: 'c4',
    name: 'ICONS Badminton & Pickleball',
    address: '122 Tôn Đản, Hòa An, Cẩm Lệ, Đà Nẵng',
    district: 'Cẩm Lệ',
    rating: 4.7,
    reviewsCount: 84,
    distance: '4.2 km',
    open: '05:00 - 24:00',
    tag: ['Đơn ngày', 'Sự kiện'],
    lat: 16.0485,
    lng: 108.1870,
    totalCourts: 6,
    priceRange: '70.000đ - 110.000đ/h',
    phone: '0905 555 777',
    amenities: ['Sân Pickleball', 'Gửi xe ô tô', 'Nước suối miễn phí'],
  },
  {
    id: 'c5',
    name: 'Trung Tâm Thể Thao Liên Châu',
    address: 'Số 7, Đường N3, Khu dân cư Bicons, Thanh Khê, Đà Nẵng',
    district: 'Thanh Khê',
    rating: 4.6,
    reviewsCount: 65,
    distance: '5.5 km',
    open: '05:00 - 22:00',
    tag: ['Đơn ngày'],
    lat: 16.0612,
    lng: 108.1950,
    totalCourts: 4,
    priceRange: '80.000đ - 100.000đ/h',
    phone: '0905 333 222',
    amenities: ['Bãi đỗ xe rộng', 'Cho thuê vợt', 'Nước giải khát'],
  },
  {
    id: 'c6',
    name: 'Sân Cầu Lông Quân Khu 5',
    address: '07 Duy Tân, Hòa Cường Bắc, Hải Châu, Đà Nẵng',
    district: 'Hải Châu',
    rating: 4.9,
    reviewsCount: 172,
    distance: '2.8 km',
    open: '05:00 - 22:30',
    tag: ['Đơn ngày', 'Sự kiện'],
    lat: 16.0460,
    lng: 108.2120,
    totalCourts: 12,
    priceRange: '90.000đ - 140.000đ/h',
    phone: '0905 777 888',
    amenities: ['Khán đài', 'Hệ thống ánh sáng chuẩn', 'Phòng thay đồ VIP'],
  },
];
